ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION MDL_MZ,MDL_ME,MDL_MW,MDL_MM,MDL_MC,MDL_MZP
     $ ,MDL_MH,MDL_MHS,MDL_MB,MDL_MT,MDL_MCHI1,MDL_MTA,MDL_MCHI2

      COMMON/MASSES/ MDL_MZ,MDL_ME,MDL_MW,MDL_MM,MDL_MC,MDL_MZP,MDL_MH
     $ ,MDL_MHS,MDL_MB,MDL_MT,MDL_MCHI1,MDL_MTA,MDL_MCHI2


      DOUBLE PRECISION MDL_WZ,MDL_WCHI2,MDL_WW,MDL_WHS,MDL_WH,MDL_WZP
     $ ,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WCHI2,MDL_WW,MDL_WHS,MDL_WH,MDL_WZP
     $ ,MDL_WT


      DOUBLE COMPLEX GC_6, GC_36, GC_38, GC_39, GC_45, GC_47, GC_48,
     $  GC_14, GC_17

      COMMON/COUPLINGS/ GC_6, GC_36, GC_38, GC_39, GC_45, GC_47, GC_48
     $ , GC_14, GC_17

